"""
Configuration file for Virtual Mouse
"""

HAND_DETECTION_CONFIDENCE = 0.7
HAND_TRACKING_CONFIDENCE = 0.7
MAX_HANDS = 2

DISTANCE_THRESHOLD = 30  
CLICK_COOLDOWN = 0.3  
SCROLL_COOLDOWN = 0.2  
SCROLL_AMOUNT = 3  


FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
SHOW_FPS = True
SHOW_LANDMARKS = True


CURSOR_SMOOTHING = 0.01  
